name: Unity Tests

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  tests:
    name: Run Unity EditMode and PlayMode suites
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/packages-lock.json') }}

      - name: Run Unity Test Runner
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: .
          unityVersion: 2022.3.0f1
          testMode: all

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unity-test-results
          path: artifacts
